# fly.toml app configuration file generated for subyrubydo on 2024-06-10T22:30:37-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'subyrubydo'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '0.25gb'
  cpu_kind = 'shared'
  cpus = 1
